version: '3.8'

services:
  backend:
    build:
      context: ./streamify-backend
    ports:
      - "8080:8080"
    volumes:
      - shared-uploads:/app/uploads
      - shared-processed:/app/processed
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: streamifydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  worker:
    build:
      context: ./streamify-worker
    depends_on:
      - redis
    volumes:
      - shared-uploads:/app/uploads
      - shared-processed:/app/processed

    env_file:
      - .env

volumes:
  pgdata:
  shared-uploads:
  shared-processed:
