version: '3.8'

services:
  backend:
    build:
      context: ./streamify-backend
    ports:
      - "8080:8080"
    volumes:
      - ./streamify-backend/uploads:/app/uploads
      - ./streamify-backend/processed:/app/processed
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: streamifydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
